[package]
name = "livesplit-auto-splitting"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
bstr = "0.2.12"
log = "0.4.8"
wasmtime = { version = "0.26.0", default-features = false }
wasmtime-wasi = { version = "0.26.0", default-features = false }
wasi-common = { version = "0.26.0", default-features = false }
wasi-cap-std-sync = { version = "0.26.0", default-features = false }
slotmap = "1.0.2"
sysinfo = "0.20.5"
read-process-memory = "0.1.3"
